services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WebHookBundle\Installer\WebHookBundleInstaller:
        public: true
        arguments:    
            $bundle: "@=service('kernel').getBundle('WebHookBundle')"
