name: Compile and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the stack
      run: docker-compose up -d
      
    - name: compile.sh
      run: docker-compose exec -T php sh src/WebHookBundle/compile.sh
      
    - name: test
      run: docker-compose exec -T -w /var/www/html/src/WebhookBundle/tests/ php /var/www/html/vendor/bin/simple-phpunit --filter testB WebHookTest.php

      
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
